footprint: [[-0.16,-0.15], [-0.16,0.15], [0.45,0.15], [0.45,-0.15]]

obstacle_layer:
   observation_sources: scan
   scan: 
      sensor_frame: /laser
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      expected_update_rate: 10.0
   obstacle_range: 2.5
   raytrace_range: 3.0

inflation_layer:
   inflation_radius: 0.6
