global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 1.0
rolling_window: true
width: 4.0
height: 4.0
resolution: 0.05

plugins:
#   - name: obstacle_layer
#     type: "costmap_2d::ObstacleLayer"
   - name: footprint_layer
     type: "costmap_2d::FootprintLayer"
   - name: inflation_layer
     type: "costmap_2d::InflationLayer"
